# Generated by Django 4.0.2 on 2025-06-09 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='created_at',
            field=models.DateTimeField(default=datetime.time(11, 47, 52, 285933)),
        ),
    ]
