# Generated by Django 4.0.2 on 2025-06-09 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_player_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='created_at',
            field=models.DateTimeField(default=datetime.time(11, 55, 53, 949133)),
        ),
    ]
